# Generated by Django 3.1.4 on 2021-01-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=1000)),
                ('mobile', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('role', models.CharField(max_length=20)),
                ('dt', models.CharField(max_length=1000)),
            ],
        ),
    ]
